<a href="https://colab.research.google.com/github/buenaflorJ-nine/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [32]:
#Arrays
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

#a.) AB
print("A")
print(A, "\n")
print("B")
print(B, "\n")
print("AB =")
print(np.dot(A,B), "\n")

#b.) D+D
print("D")
print(D, "\n")
print("D + D =")
print(np.add(D,D), "\n")

#c.) 2C
print("C")
print(C, "\n")
print("2C =")
print(np.multiply(2,C))

A
[[1 2 3]
 [4 5 6]] 

B
[[1 2]
 [3 4]
 [5 6]] 

AB =
[[22 28]
 [49 64]] 

D
[[1 2]
 [3 4]] 

D + D =
[[2 4]
 [6 8]] 

C
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

2C =
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Question 2

In [33]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
print("A =", A)
print("B =", B)
print("The cross product is:", np.cross(A,B))

A = [2 7 4]
B = [3 9 8]
The cross product is: [20 -4 -3]
