<a href="https://colab.research.google.com/github/buenaflorJ-nine/58013-Linear-Algebra/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
print(int(np.linalg.det(A)))

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
print(int(np.linalg.det(B)))



3
-235


Coding Activity 9

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,3],[4,4,7],[1,1,1]])
z = np.array([[2,4,6],[2,5,7],[1,2,2]])
print(x, "\n")
print(y, "\n")
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3 3]
 [4 4 7]
 [1 1 1]] 

[[2 4 6]
 [2 5 7]
 [1 2 2]]


Distributive Property

In [4]:
# 1. Distributive Property

a = x.dot(y + z)

b = x.dot(y) + x.dot(z)

print("x(y + z) =", "\n",a)
print("xy + xz =", "\n",b)
print(np.array_equal(a,b))

x(y + z) = 
 [[ 22  34  46]
 [ 58  91 124]
 [ 94 148 202]]
xy + xz = 
 [[ 22  34  46]
 [ 58  91 124]
 [ 94 148 202]]
True


Associative Property

In [5]:
a = (x.dot(y)).dot(z)
b = x.dot(y.dot(z))

print("(xy)z =", "\n", a)
print("x(yz) =", "\n",b)
print(np.array_equal(a,b))

(xy)z = 
 [[ 74 162 216]
 [197 432 576]
 [320 702 936]]
x(yz) = 
 [[ 74 162 216]
 [197 432 576]
 [320 702 936]]
True


Scalar Multiplication Distributive Property

In [6]:
Scale = 2

a = Scale*(z.dot(y))
b = (Scale*z).dot(y)

print("Scale(xy) =", "\n",a)
print("(Scale*x)y =", "\n",b)
print(np.array_equal(a,b))

Scale(xy) = 
 [[52 56 80]
 [62 66 96]
 [24 26 38]]
(Scale*x)y = 
 [[52 56 80]
 [62 66 96]
 [24 26 38]]
True


Identity Matrix Property

In [ ]:
Identity = np.identity(3)

a = Identity.dot(x)
b = x.dot(Identity)

print("Identity*x =", "\n",a)
print("x*Identity =", "\n",b)

print(np.array_equal(b, x) and np.array_equal(b, x))

Identity*x = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
x*Identity = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
True


Multiplicative Property of Zero

In [9]:
zero = np.zeros((3, 3))

a = zero.dot(x)
b = x.dot(zero)

print("0x =", "\n", a)
print("xy =", "\n", b)

print(np.array_equal(a, zero) and np.array_equal(b, zero))


0x = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ay = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
True


Transpose Property

In [13]:
a = (x.dot(y)).T
b = (y.T).dot(x.T)

print("(xy)^T =", "\n", a)
print("y^T * x^T =", "\n", b)

print(np.array_equal(a, b))

(xy)^T = 
 [[13 34 55]
 [14 38 62]
 [20 53 86]]
y^T * x^T = 
 [[13 34 55]
 [14 38 62]
 [20 53 86]]
True
