<a href="https://colab.research.google.com/github/buenaflorJ-nine/58013-Linear-Algebra/blob/main/System_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]], dtype=float)
print(X)
print(X.shape, "\n")
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3) 

[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


Coding Activity 10

In [20]:
Supply=np.array([[30,10,120],[40,20,200],[50,40,360]])

Cost = np.array([12500,18000,25700])

prices = np.linalg.solve(Supply, Cost)
flour, yeast, egg = prices

print(f"Price per 1 sack of flour: {flour:.2f} pesos")
print(f"Price per 1 pack of yeast: {yeast:.2f} pesos")
print(f"Price per 1 egg: {egg:.2f} pesos")

Price per 1 sack of flour: 330.00 pesos
Price per 1 pack of yeast: 140.00 pesos
Price per 1 egg: 10.00 pesos
