<a href="https://colab.research.google.com/github/buenaflorJ-nine/58013-Linear-Algebra/blob/main/Vector%2CSpaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


Describing vectors in NumPy -
Size, Dimension, Size

In [19]:
import numpy as np

# Checking Shapes
# Shapes tells us how many rows and columns are there

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball + balls
print(z)
x = np.ndim
print(x)

[1 2 3]
[ 0  1 -1]
(3, 3)
<function ndim at 0x78dcc5b2bd00>


Addition

In [21]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(A+B)
print(R)

[ 6 -2]
[ 6 -2]


Subtraction

In [23]:
R1 = np.subtract(A,B)
print(R1)
R2 = np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


Scalar Product

In [24]:
S = np.array([2])
V = S*A
print(V)

[8 6]


Dot Product

In [30]:
print(np.dot(A,B))

-7


Properties of Matrix

In [44]:
#Identity Matrix
c = np.eye(3,3)
print(c)
#Zero Matrix
d = np.zeros([5,5])
print(d)
#Full Matrix
e = np.full((3,3), 7)
print(e)
#Transpose Matrix
f = np.transpose(A)
print(A)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
